name: Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+-tetrate-v[0-9]+' ]  # v1.16-tetrate-v7

env:
  GOPROXY: https://proxy.golang.org

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    env:
      IMG: tetrate/kubegres:${{  github.ref_name }}
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker-build-push
